version: '3'
services:
  # rails:
  #   container_name: rails
  #   build: .
  #   depends_on:
  #     - db
  #   volumes:
  #     - .:/app
  #   ports:
  #     - '3000:3000'
  #   env_file:
  #     - .env
  #   command: bundle exec rails server -p 3000 -b '0.0.0.0'
  db:
    image: postgres:latest
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
